#!/bin/sh
set -e
git update-server-info
git pack-refs --all
for name in refs/*; do
	[ "$name" != refs/heads ] || continue
	[ "$name" != refs/tags ] || continue
	[ -d "$name" ] || continue
	rmdir "$name"
done
